bones_mode = drop

flame_sound = true

give_initial_stuff = true
initial_stuff = default:pick_wood,default:axe_wood,default:shovel_wood,default:torch 5,default:apple 42
enable_bed_respawn = true
enable_bed_night_skip = true
enable_fence_tall = true
river_source_sounds = false
pbj_pup_generate = true
enable_tnt = true
toolranks_levels = 80

[Nether depth]
#The depth where the Nether begins / the Nether ceiling
nether_depth_ymax = -4000
#The lower limit of the Nether must be at least 1000 lower than the upper limit, and more than 3000 lower is recommended.
nether_depth_ymin = -6666

spawnrand.radius_area = 3000

unified_inventory_trash = false
unified_inventory_hide_disabled_buttons = true
